// Auto-generated from the original site content — list of conditions treated.
export const CONDITIONS = [
  { condition: "Asthma", symptoms: "Wheezing, shortness of breath, chest tightness, and recurring cough." },
  { condition: "Arthritis & Joint Pain", symptoms: "Joint stiffness, swelling, tenderness, reduced mobility, and recurring pain." },
  { condition: "Digestive Disorders", symptoms: "Bloating, indigestion, abdominal discomfort, irregular bowel movements, and nausea." },
  { condition: "Skin Diseases", symptoms: "Itching, irritation, dryness, rashes, inflammation, and recurring skin complaints." },
  { condition: "Hormonal Imbalances", symptoms: "Mood changes, fatigue, irregular cycles, weight changes, and other hormone-related symptoms." },
  { condition: "Anxiety & Depression", symptoms: "Persistent worry, low mood, restlessness, sleep difficulty, and reduced concentration." },
  { condition: "Migraine & Headache", symptoms: "Throbbing headache, sensitivity to light or sound, nausea, and recurring head pain." },
  { condition: "Allergies", symptoms: "Sneezing, runny nose, itching, watery eyes, and sensitivity to common triggers." },
  { condition: "Sinusitis", symptoms: "Nasal congestion, facial pressure, headache, post-nasal drip, and sinus discomfort." },
  { condition: "Eczema", symptoms: "Dry or sensitive skin, itching, redness, scaling, and recurring irritation." },
  { condition: "Psoriasis", symptoms: "Scaly patches, redness, itching, dryness, and recurring skin flare-ups." },
  { condition: "Acne", symptoms: "Pimples, blackheads, whiteheads, inflammation, and recurring breakouts." },
  { condition: "Respiratory Issues", symptoms: "Persistent cough, congestion, throat irritation, wheezing, and breathing discomfort." },
  { condition: "Thyroid Problems", symptoms: "Fatigue, temperature sensitivity, weight changes, mood changes, and related symptoms." },
  { condition: "PCOS", symptoms: "Irregular periods, acne, excess hair growth, and other symptoms associated with PCOS." },
  { condition: "Menstrual Disorders", symptoms: "Irregular cycles, cramps, heavy bleeding, mood changes, and menstrual discomfort." },
  { condition: "Gastritis", symptoms: "Upper abdominal discomfort, nausea, bloating, and burning or fullness after meals." },
  { condition: "Acidity & Reflux", symptoms: "Heartburn, sour taste, chest/upper-abdominal burning, and reflux after meals." },
  { condition: "Constipation", symptoms: "Infrequent bowel movements, hard stools, straining, and abdominal discomfort." },
  { condition: "IBS", symptoms: "Abdominal pain, bloating, and recurring changes in bowel habits." },
  { condition: "Piles", symptoms: "Discomfort, itching, swelling, and bleeding associated with hemorrhoids." },
  { condition: "Urinary Problems", symptoms: "Frequent urination, urgency, burning, discomfort, and other urinary symptoms." },
  { condition: "Kidney Complaints", symptoms: "Flank discomfort, urinary changes, swelling, or recurring kidney-related complaints." },
  { condition: "Joint/Back/Neck Pain", symptoms: "Localized pain, stiffness, muscle tension, and reduced movement." },
  { condition: "Insomnia", symptoms: "Difficulty falling asleep, frequent waking, poor sleep quality, and daytime tiredness." },
  { condition: "Stress & Nervousness", symptoms: "Restlessness, tension, difficulty relaxing, irritability, and sleep disturbance." },
  { condition: "Chronic Fatigue", symptoms: "Persistent tiredness, low energy, reduced stamina, and difficulty maintaining daily activity." },
  { condition: "Immunity Support", symptoms: "General wellness support and healthy lifestyle guidance for maintaining normal immune function." },
];
